import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faCircle,
  faMinus,
  faPlus,
  faXmark
} from '@fortawesome/free-solid-svg-icons'
import {
  faAlarmClock as fadAlarmClock,
  faArrowsToCircle as fadArrowsToCircle,
  faBrainCircuit as fadBrainCircuit,
  faBell as fadBell,
  faBook as fadBook,
  faBooks as fadBooks,
  faBookUser as fadBookUser,
  faBoxArchive as fadBoxArchive,
  faBuilding as fadBuilding,
  faBuildingShield as fadBuildingShield,
  faBullseye as fadBullseye,
  faCalendarDays as fadCalendarDays,
  faChartColumn as fadChartColumn,
  faCircleCheck as fadCircleCheck,
  faCircleDot as fadCircleDot,
  faCircleExclamation as fadCircleExclamation,
  faCircleInfo as fadCircleInfo,
  faCircleO as fadCircleO,
  faCirclePlus as fadCirclePlus,
  faCircleXmark as fadCircleXmark,
  faClipboardListCheck as fadClipboardListCheck,
  faClipboardUser as fadClipboardUser,
  faClock as fadClock,
  faCube as fadCube,
  faComments as fadComments,
  faDiagramSubtask as fadDiagramSubtask,
  faDownload as fadDownload,
  faEnvelopesBulk as fadEnvelopesBulk,
  faEye as fadEye,
  faFile as fadFile,
  faFileCertificate as fadFileCertificate,
  faFileCheck as fadFileCheck,
  faFileLines as fadFileLines,
  faFilePen as fadFilePen,
  faFilePlus as fadFilePlus,
  faFileShield as fadFileShield,
  faFileZipper as fadFileZipper,
  faFloppyDisk as fadFloppyDisk,
  faFolder as fadFolder,
  faFolderBookmark as fadFolderBookmark,
  faGlobe as fadGlobe,
  faGlobePointer as fadGlobePointer,
  faHeadSideBrain as fadHeadSideBrain,
  faHistory as fadHistory,
  faHourglassStart as fadHourglassStart,
  faHouse as fadHouse,
  faHouseMedicalFlag as fadHouseMedicalFlag,
  faInbox as fadInbox,
  faInboxIn as fadInboxIn,
  faInboxOut as fadInboxOut,
  faLandmark as fadLandmark,
  faLaptopMobile as fadLaptopMobile,
  faLocationDot as fadLocationDot,
  faLockKeyhole as fadLockKeyhole,
  faMagnifyingGlass as fadMagnifyingGlass,
  faMegaphone as fadMegaphone,
  faMemoCircleInfo as fadMemoCircleInfo,
  faMemoPad as fadMemoPad,
  faMessages as fadMessages,
  faMicrochip as fadMicrochip,
  faMobile as fadMobile,
  faMoneyBills as fadMoneyBills,
  faMoneyFromBracket as fadMoneyFromBracket,
  faNewspaper as fadNewspaper,
  faPaperPlaneTop as fadPaperPlaneTop,
  faPencilLine as fadPencilLine,
  faPenToSquare as fadPenToSquare,
  faPeopleGroup as fadPeopleGroup,
  faPollPeople as fadPollPeople,
  faRectangleBarcode as fadRectangleBarcode,
  faReceipt as fadReceipt,
  faScaleBalanced as fadScaleBalanced,
  faShapes as fadShapes,
  faShareNodes as fadShareNodes,
  faShieldCheck as fadShieldCheck,
  faShieldHalved as fadShieldHalved,
  faShieldUser as fadShieldUser,
  faSquarePollVertical as fadSquarePollVertical,
  faThumbsUp as fadThumbsUp,
  faTimesCircle as fadTimesCircle,
  faTrafficCone as fadTrafficCone,
  faTrashCan as fadTrashCan,
  faTriangleExclamation as fadTriangleExclamation,
  faUser as fadUser,
  faUserCrown as fadUserCrown,
  faUserPoliceTie as fadUserPoliceTie,
  faUserTieHair as fadUserTieHair,
  faWhistle as fadWhistle
} from '@fortawesome/pro-duotone-svg-icons'

library.add(
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faCircle,
  faMinus,
  faPlus,
  faXmark
)

library.add(
  fadAlarmClock,
  fadArrowsToCircle,
  fadBrainCircuit,
  fadBell,
  fadBook,
  fadBooks,
  fadBookUser,
  fadBoxArchive,
  fadBuilding,
  fadBuildingShield,
  fadBullseye,
  fadCalendarDays,
  fadChartColumn,
  fadCircleCheck,
  fadCircleDot,
  fadCircleExclamation,
  fadCircleInfo,
  fadCircleO,
  fadCirclePlus,
  fadCircleXmark,
  fadClipboardListCheck,
  fadClipboardUser,
  fadClock,
  fadCube,
  fadComments,
  fadDiagramSubtask,
  fadDownload,
  fadEnvelopesBulk,
  fadEye,
  fadFile,
  fadFileCertificate,
  fadFileCheck,
  fadFileLines,
  fadFilePen,
  fadFilePlus,
  fadFileShield,
  fadFileZipper,
  fadFloppyDisk,
  fadFolder,
  fadFolderBookmark,
  fadGlobe,
  fadGlobePointer,
  fadHeadSideBrain,
  fadHistory,
  fadHourglassStart,
  fadHouse,
  fadHouseMedicalFlag,
  fadInbox,
  fadInboxIn,
  fadInboxOut,
  fadLandmark,
  fadLaptopMobile,
  fadLocationDot,
  fadLockKeyhole,
  fadMagnifyingGlass,
  fadMegaphone,
  fadMemoCircleInfo,
  fadMemoPad,
  fadMessages,
  fadMicrochip,
  fadMobile,
  fadMoneyBills,
  fadMoneyFromBracket,
  fadNewspaper,
  fadPaperPlaneTop,
  fadPencilLine,
  fadPenToSquare,
  fadPeopleGroup,
  fadPollPeople,
  fadRectangleBarcode,
  fadReceipt,
  fadScaleBalanced,
  fadShapes,
  fadShareNodes,
  fadShieldCheck,
  fadShieldHalved,
  fadShieldUser,
  fadSquarePollVertical,
  fadThumbsUp,
  fadTimesCircle,
  fadTrafficCone,
  fadTrashCan,
  fadTriangleExclamation,
  fadUser,
  fadUserCrown,
  fadUserPoliceTie,
  fadUserTieHair,
  fadWhistle
)
